name: Build and Deploy application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy First Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # check the code on the github and upload on the ubuntu

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        uses: mvn -B test --file pom.xml

      - name: Build
        uses: |
          mvn clean
          mvn -B package --file pom.xml