name: Build and Deploy application

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy First Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Check out the code on GitHub and upload it to Ubuntu

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: |
          mvn clean
          mvn -B package --file pom.xml

