name: Build and Deploy application

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy First Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Check out the code on GitHub and upload it to Ubuntu

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-practice:$(date +'%Y%m%d%H%M%S') .
        env:
          DOCKER_BUILDKIT: 1

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ci-cd-practice:$(date +'%Y%m%d%H%M%S')
        
